# Generated by Django 2.1.3 on 2018-11-25 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='participantes',
            new_name='participantesChat',
        ),
        migrations.AddField(
            model_name='saladechat',
            name='topico',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
